# Generated by Django 3.1.2 on 2020-10-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_process', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='file',
            new_name='image',
        ),
    ]
