# Generated by Django 3.1.2 on 2020-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_process', '0002_auto_20201027_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
    ]
