# Generated by Django 3.1.2 on 2020-11-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_process', '0003_imagefile_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlurredImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_binary', models.BinaryField()),
            ],
            options={
                'db_table': 'applyblur',
                'managed': False,
            },
        ),
    ]
